name: task08 CI

on:
  push:
    branches: [ task08 ]  
  pull_request:
    branches: [ task08 ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 
    
    - name: restore
      run: dotnet restore
    
    - name: build
      run: dotnet build --configuration Release --no-restore
    
    - name: test
      run: dotnet test --no-build --configuration Release
